### ISSUE TITLE
How to use apollo client properly into nextjs for SSR Data fetching? (Unique Problem)

### ISSUE THREAD

**Issue by siamahnaf** [apollographql/apollo-client#10936]
In nextjs, I am using getServerSideProps for fetching data-

```
export const getServerSideProps: GetServerSideProps = async (ctx) => {
    const apolloClient = initializeApollo()
    const { data } = await apolloClient.query({
        query: GET_SECTION_LIST,
        variables: { searchInput: {} },
        context: {
            headers: {
                cookie: ctx.req.headers.cookie,
                "user-agent": ctx.req.headers["user-agent"],
                "x-forwarded-for": ctx.req.socket.remoteAddress
            }
        },
        fetchPolicy: "network-only"
    });
    return addApolloState(apolloClient, {
        props: {},
    })
}
```

I need realtime on every request, that's why I use `network-only` as fetch policy. Here be note that, I also need the page SSR render with fetched data and I also need realtime data when I navigate internally into nextjs. As the video I give, I have some section data, I go the group page. Suddenly I delete a section data from databse. And then I go to the section page again, here it should update the data, as I use `network-only` as fetch policy. But getServerSideProps function fetching the update data, then why apollo-client not update the previous cached?

https://github.com/apollographql/apollo-client/assets/78312010/d5106c4d-2df1-49ae-854c-c1b5633402c0

Here is my code-

```
client.ts-
import { useMemo } from "react";
import {
    ApolloClient,
    InMemoryCache,
    type NormalizedCacheObject,
} from '@apollo/client';
import merge from 'deepmerge';
import isEqual from 'lodash-es/isEqual';

const COUNTRIES_API = 'http://localhost:3001/ecampus';

const APOLLO_STATE_PROP_NAME = '__APOLLO_STATE__';

let apolloClient: ApolloClient<NormalizedCacheObject> | null;

function createApolloClient() {
    return new ApolloClient({
        ssrMode: typeof window === 'undefined',
        uri: COUNTRIES_API,
        cache: new InMemoryCache(),
        credentials: 'include'
    });
}

export function initializeApollo(initialState?: any) {
    const _apolloClient = apolloClient ?? createApolloClient();

    if (initialState) {
        const existingCache = _apolloClient.cache.extract();

        const data = merge(initialState, existingCache, {
            arrayMerge: (destinationArray, sourceArray) => [
                ...sourceArray,
                ...destinationArray.filter((d) =>
                    sourceArray.every((s) => !isEqual(d, s))
                ),
            ],
        });
        _apolloClient.cache.restore(data);
    }

    if (typeof window === 'undefined') {
        return _apolloClient;
    }

    if (!apolloClient) {
        apolloClient = _apolloClient;
    }

    return _apolloClient;
}

export function addApolloState(
    client: ApolloClient<NormalizedCacheObject>,
    pageProps: any
) {
    if (pageProps?.props) {
        pageProps.props[APOLLO_STATE_PROP_NAME] = client.cache.extract();
    }

    return pageProps;
}

export function useApollo(pageProps: any) {
    const state = pageProps[APOLLO_STATE_PROP_NAME];
    const client = useMemo(() => initializeApollo(state), [state]);
    return client;
}
```

_app.tsx-

```
export default function App({ Component, pageProps }: AppProps) {
  const apolloClient = useApollo(pageProps);
  return (
    <ApolloProvider client={apolloClient}>
      <main className={`${inter.variable} font-sans`}>
        <Component {...pageProps} />
      </main>
    </ApolloProvider>
  )
}
```

And In one component of my page-

`const sectionsData = useQuery<GetSectionListData>(GET_SECTION_LIST, { variables: { searchInput: {} } });`

Here is my full code- https://github.com/siamahnaf/apollo-test

**Comment by phryneas** [comment]
`network-only` means that the result will not be written to the cache.

As you are doing SSR here, and creating a new, empty, Apollo Client for each request, I don't believe that you really need a `network-only` cache policy. The cache will be empty, so it will make a network request. 
So try it without that cache policy? That should be working fine.

**Comment by siamahnaf** [comment]
Thank you for respose

As your reply, I remove fetch policy and try it. It perform same problem as I show in video.

Sorry: `So try it without that cache policy?` here I think mean fetch policy. If it will be fetch policy then it working still. If it will be carch policy then I can't understand how I can remove cache policy and form where?

**Comment by siamahnaf** [comment]
Here, I try to remove `fetchPolicy: "network-only"` from getServerSideProps, but it still not working.

**Comment by phryneas** [comment]
Rewatching your video, I could be wrong there, but I think for this type of in-app navigation, Next SSR won't even be rendering again, so your `getServerSideProps` might not even re-execute? Maybe log a typestamp to see that.

**Comment by siamahnaf** [comment]
I console data in two place

1. In the `getServerSideProps` :-
Here into `getServerSideProps` function, I console data. It gives me the updated data on every request.

2. In component where I use `useQuery` hook:-
here I am getting previous data, `useQuery` hook not giving the updated data that already fetched in getServerSideProps


That's means, I am wrong some where when I merging data. `useQuery` not getting updated data?

**Comment by phryneas** [comment]
Maybe log the `data` before you call `        _apolloClient.cache.restore(data);` ?

`client.cache.restore` should replace the full cache contents.

**Comment by siamahnaf** [comment]
Update my github code with live api url. Would you please run my code on your system give the wrongs, I do in my code?

**Comment by phryneas** [comment]
That confirms what I already had suspected - that data is not transported from the server to the client for in-app-navigation, only for the initial page load. 
You will have to set a `fetchPolicy` that will re-request that data on remount of your component. This doesn't really have to do anything with SSR.

**Comment by siamahnaf** [comment]
Where I have to set `fetchPolicy`, `useQuery` hook or `getServerSideProps`?

**Comment by jerelmiller** [comment]
@phryneas slight correction on this statement:

> `network-only` means that the result will not be written to the cache.

`network-only` _will_ write to the cache, it just ignores that cached result when determining whether it should fetch or read from the cache. `no-cache` is the only fetch policy that prevents writing to the cache. See [this chart](https://www.apollographql.com/docs/react/data/queries/#supported-fetch-policies) for the full descriptions of each.

**Comment by siamahnaf** [comment]
If I set fetchpolicy  then ssr render not working?

**Comment by bignimbus** [comment]
@siamahnaf you'll need to add a conditional:

> You will have to set a fetchPolicy that will re-request that data on remount of your component. This doesn't really have to do anything with SSR.

I believe you'd need add a `fetchPolicy` in the `useQuery` call that's being assigned to `sectionsData`.  Closing this for now, please feel free to ask implementation questions in our [discord](https://discord.gg/graphos) or [forum](https://community.apollographql.com) 🙏🏻  thanks!
