### ISSUE TITLE
refetchQueries with string arguments not updating component

### ISSUE THREAD

**Issue by dmarkow** [apollographql/apollo-client#1561]
**Intended outcome:**
Given a query:
```
const AllUsersQuery = gql`
  query AllUsers {
    users {
      id
      login
    }
  }
`;
```

Using ```refetchQueries: ["AllUsers"]``` in a mutation should re-execute the query and update any components depending on that query.

**Actual outcome:**
While the query is re-executed, the component never updates. Using the apollo dev tools in Chrome, I can see the new User item listed in the store, but it never makes it to my component.

If I instead import the original query variable and use `refetchQueries: [{query: AllUsersQuery}]`, everything works as expected.

**How to reproduce the issue:**
Use string arguments in `refetchQueries`

**Comment by saudpunjwani101** [comment]
refetchQueries takes a query object, I don't think u can actually pass a string to it.

**Comment by dmarkow** [comment]
@saudpunjwani101 [The documentation on refetchQueries](http://dev.apollodata.com/react/api-mutations.html#graphql-mutation-options-refetchQueries) says it can take an array of either strings or objects (and the first example uses the string option).

**Comment by saudpunjwani101** [comment]
Yeah ur right, although the query does re execute it's not resolving the updates. I'll try it

**Comment by helfer** [comment]
@dmarkow could you provide a reproduction for this?

**Comment by MichaelDeBoey** [comment]
@dmarkow If your get back a union, then this could be the same problem as in #1611, which is fixed by #1638 :-)

**Comment by dmarkow** [comment]
I just tried to reproduce this on the current version and can't, so maybe it was resolved with some of the recent updates... Thanks!

**Comment by ctavan** [comment]
Might be related to the race-condition described in #1821.

**Comment by jpikora** [comment]
I've just come across the same issue as @dmarkow.

Object format `[{ query: ... }, ...]` for refetchQueries is working correctly, but when using Strings `['queryName', ...]` the store is not updated, even though the refetch requests are correctly executed.

`apollo-client@2.2.0`

**Comment by ctavan** [comment]
@jpikora I still believe that this is the race condition outlined in #1821

**Comment by jcace** [comment]
Any update on this? I still can't pass string arguments to refetchQueries, as they don't seem to update the cache. Apollo client v2.6.8
