### ISSUE TITLE
Uncaught DOMException: Failed to execute 'postMessage' on 'Window'

### ISSUE THREAD

**Issue by jazzdragon** [apollographql/apollo-client#1879]
* could be related to [#1871](https://github.com/apollographql/apollo-client/issues/1871)

I have afterware on my apollo client to handle errors in my app. In order to check the server's response status I have to clone the response. It was working fine until suddenly (chrome update?) I started getting this message:
`DOMException: Failed to execute 'postMessage' on 'Window': Error: Network request failed with status 401 - "Unauthorized" could not be cloned.`
(the error is the response from the server).

To replicate, create an afterware that clones the response from the server.

Thanks!

**Comment by dcworldwide** [comment]
Updated to latest, also getting:

```
VM57:13 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': DOMException object could not be cloned.
    at ApolloClient.hookLogger [as devToolsHookCb] (<anonymous>:13:12)
    at http://localhost:3000/vendor.378cdad4168a0cb6b158.js:78529:27
    at Object.dispatch (http://localhost:3000/vendor.378cdad4168a0cb6b158.js:24413:16)
    at QueryManager.fetchQuery (http://localhost:3000/vendor.378cdad4168a0cb6b158.js:78803:20)
    at QueryManager.startQuery (http://localhost:3000/vendor.378cdad4168a0cb6b158.js:79108:14)
    at ObservableQuery.setUpQuery (http://localhost:3000/vendor.378cdad4168a0cb6b158.js:24197:27)
    at ObservableQuery.onSubscribe (http://localhost:3000/vendor.378cdad4168a0cb6b158.js:24149:18)
    at ObservableQuery.subscriberFunction (http://localhost:3000/vendor.378cdad4168a0cb6b158.js:23923:26)
    at ObservableQuery.Observable.subscribe (http://localhost:3000/vendor.378cdad4168a0cb6b158.js:50196:50)
    at GraphQL.subscribeToQuery (http://localhost:3000/app.378cdad4168a0cb6b158.js:16621:63)
```

**Comment by jameswyse** [comment]
Seems to be a problem with the apollo devtools. Had to disable the extension in chrome.

**Comment by jazzdragon** [comment]
Yep, that worked, thanks.
Leaving this open until the issue is resolved.

**Comment by batjko** [comment]
I'm seeing something similar, but with `Error writing result to store for query` as the underlying error:

```bash
Caught an exception! DOMException: Failed to execute 'postMessage' on 'Window': Error: Error writing result to store for query
```
Disabling the extension solved the issue for me as well.

**Comment by jbaxleyiii** [comment]
@ramyanaga have we fixed this?

**Comment by jbaxleyiii** [comment]
@jazzdragon I'm going to close this and move it to the Apollo-devtools repo 👍  thanks!

**Comment by blackinno** [comment]
This my case 
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': Error: GraphQL error: Whoops. Looks like an internal server error

**Comment by timbrandin** [comment]
I'm getting the same error, I don't even have apollo devtools installed in my browser (using chrome).

**Comment by shahzeb1** [comment]
![image](https://user-images.githubusercontent.com/1383831/32206382-ea66de90-bdb1-11e7-9da2-2460105528de.png)

Still getting this error (don't have the Chrome extension installed). Any guesses?

**Comment by ste93cry** [comment]
Same here, after a mutation throws an error (user error) I get the message 

>DOMException: Failed to execute 'postMessage' on 'Window': Error: GraphQL error

I'm using Chrome with the Apollo Dev Tools enabled

**Comment by shahzeb1** [comment]
I finally got it to work, this is what my client related code looks like. Hope it helps someone.

```js
const token = localStorage.getItem('id_token'); 
const middleware = new ApolloLink((operation, forward) => {
  // add the authorization to the headers
  operation.setContext({
    headers: {
      Authorization: `Bearer ${token}`,
    } 
  });
  return forward(operation);
})

const client = new ApolloClient({
  link: concat(middleware, httpLink),
  cache: new InMemoryCache({
    dataIdFromObject: o => o.uuid
  })
});
```
