### ISSUE TITLE
Fetch policy no-cache returns null data

### ISSUE THREAD

**Issue by razor-x** [apollographql/apollo-client#3030]
**Intended outcome:**

Run a query and receive non-null data when using `fetchPolicy: 'no-cache'`. Tested on Node and in Browser.

```js
client.query({query, fetchPolicy: 'no-cache'})
```

**Actual outcome:**

The `data` property is `null`:

```js
{
  data: null
  loading: false
  networkStatus: 7
  stale: true
}
```

**How to reproduce the issue:**

#### Node.js

1. Visit this runkit and fork it: https://runkit.com/razorx/apollo-client-no-cache/4.0.1
2. Run the first box to initialize.
3. Run the second box to run a query with the default fetch policy: the Promise will eventually resolve with good data (`data: {...}` ). (expected)
4. Run the second box to run a query with the `no-cache` fetch policy: the Promise will eventually resolve with no data (`data: null`). (unexpected)
5. Run the second box to run a query with the `network-only` fetch policy: the Promise will eventually resolve with good data. (expected)

#### Browser

1. Visit https://codesandbox.io/s/znx9n9x943
2. Run the code with the "refresh" button in the right pane.
    - `clientA` works with default fetch policy: returns non-null data. (expected)
    - `clientB` does not work with `no-cache` fetch policy: returns `null` data. (unexpected)
    - `clientC` works with default fetch policy (returns non-null data), then the **query is repeated again with `clientC`, this time with `no-cache` fetch policy, and the data returns non-null!** (what?)

**Version**
- apollo-client@2.2.3

**Contents of the runkit for reference**

```js
require('isomorphic-fetch')
require('graphql')
const { ApolloClient } = require('apollo-client')
const { HttpLink } = require('apollo-link-http')
const { InMemoryCache } = require('apollo-cache-inmemory')
const gql = require('graphql-tag')

const uri = 'https://graphql-pokemon.now.sh/graphql'

const query = gql`{
  pokemon(name: "Pikachu") {
    id
    number
    name
  }
}`

const client = new ApolloClient({
  link: new HttpLink({uri}),
  cache: new InMemoryCache()
})

client.query({query})
  .then(data => console.log(data))
  .catch(error => console.error(error))
  
// => gives good data
  
 const clientNoCache = new ApolloClient({
  link: new HttpLink({uri}),
  cache: new InMemoryCache()
})

clientNoCache.query({query, fetchPolicy: 'no-cache'})
  .then(data => console.log(data))
  .catch(error => console.error(error))
  
// => gives NULL data

const clientNetworkOnly = new ApolloClient({
  link: new HttpLink({uri}),
  cache: new InMemoryCache()
})

clientNoCache.query({query, fetchPolicy: 'network-only'})
  .then(data => console.log(data))
  .catch(error => console.error(error))
  
// => gives good data
```

**Contents of the browser example for reference**

```js
import { gql, graphql } from 'react-apollo';
import { ApolloClient } from 'apollo-client';
import { HttpLink } from 'apollo-link-http';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { ApolloProvider } from 'react-apollo';
import App from './App';

const uri = 'https://qkv3mq9rp.lp.gql.zone/graphql'

const clientA = new ApolloClient({
  link: new HttpLink({uri}),
  cache: new InMemoryCache()
});

const clientB = new ApolloClient({
  link: new HttpLink({uri}),
  cache: new InMemoryCache()
});

const clientC = new ApolloClient({
  link: new HttpLink({uri}),
  cache: new InMemoryCache()
});

const query = gql`{
  people {
    id
    name
  }
}
`

clientA.query({query})
  .then(data => document.write('A cache<br \><br \>' + JSON.stringify(data)))
  .then(() => clientB.query({query, fetchPolicy: 'no-cache'}))
  .then(data => document.write('<br \><br \>B no-cache<br \><br \>' + JSON.stringify(data)))
  .then(() => clientC.query({query}))
  .then(data => document.write('<br \><br \>C cache<br \><br \>' + JSON.stringify(data)))
  .then(() => clientC.query({query, fetchPolicy: 'no-cache'}))
  .then(data => document.write('<br \><br \>C no-cache<br \><br \>' + JSON.stringify(data)))
  .catch(error => console.error(error))
```

**Comment by dennislaupman** [comment]
Thanks for detailed report @razor-x. I have the same issue :)

**Comment by rschef** [comment]
I had the same issue as well. I found a workaround by using react-apollo's graphql:

```javascript
import React, { Component } from 'react';
import { graphql } from 'react-apollo';

import MY_QUERY from './myQuery';

class MyComponent extends Component {
  ...
}

export default graphql(MY_QUERY, {
  options: ({ date }) => ({
    variables: { date },
    fetchPolicy: 'no-cache'
  })
})(MyComponent);

**Comment by razor-x** [comment]
@rschef I need this to work in a system which doesn't know about react and uses this client directly, so unfortunately that workaround won't be an option for me.

I poked around a little in [QueryManager.ts](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts) but I couldn't find an obvious reason for this bug. 

I'm hoping someone more familiar with the code will be able to prioritize and find this quickly. I would consider this a serious bug as I could rephrase the issue as  **apollo-client does not support the most basic GraphQL operation: running a query and returning the correct result** (without the added complexity of caching).

**Comment by kamranayub** [comment]
It's this code:

https://github.com/apollographql/apollo-client/blob/6eec674f206cda11cf667a89022354b1476f5503/packages/apollo-client/src/core/QueryManager.ts#L1096

Basically, if `fetchMoreQueryId` is not present, it tries to get the result from the cache even though it was never set (right above, `if (fetchPolicy !== "no-cache")`).

The branch needs to be updated to use `result.data` if `no-cache` is used, I think.

I'm running into this right now because the cache actually seems to be causing performance issues in our use case and I wanted to try bypassing it; but I can't due to this bug :( If I can figure out how to develop this locally, I could try updating it.

**Comment by kamranayub** [comment]
Alright, I am debugging this issue actively.

I think my "fix" will work, however there's another problem.

In QueryManager, the `queryListenerForObserver` will check the `lastResult` of the ObservableQuery. When using anything other than `no-cache` fetchPolicy, the above code will write to the data store. Then, right here, if `lastResult` ends up being null/undefined, the code assumes the data exists in the store and uses that. Hence, even with my fix, it doesn't work because `queryListenerForObserver` will call `observer.next()` with the null data **before** `fetchRequest` calls complete and `resolve` with the actual data from the network request.

I'm a little disappointed, because a simple test showcases this bug. 

```
it('supports no-cache fetchPolicy query', () => {
    const nonCachedQuery = gql`
      query nonCachedQuery {
        luke: people_one(id: 1) {
          name
        }
      }
    `;

    const data1 = {
      luke: {
        name: 'Luke Skywalker',
      },
    };

    const queryManager = mockQueryManager({
      request: { query: nonCachedQuery },
      result: { data: data1 },
    });

    return queryManager.query<any>({
      query: nonCachedQuery,
      fetchPolicy: 'no-cache',
    }).then(result => {
      expect(result.data['luke'].name).toBe('Luke Skywalker');
    });
  });

  it('supports no-cache fetchPolicy watchQuery', () => {
    const nonCachedQuery = gql`
      query nonCachedQuery {
        luke: people_one(id: 1) {
          name
        }
      }
    `;

    const data1 = {
      luke: {
        name: 'Luke Skywalker',
      },
    };

    const queryManager = mockQueryManager({
      request: { query: nonCachedQuery },
      result: { data: data1 },
    });

    return queryManager.watchQuery<any>({
      query: nonCachedQuery,
      fetchPolicy: 'no-cache',
    }).result().then(result => {
      console.log(result);
      expect(result.data['luke'].name).toBe('Luke Skywalker');
    });
  });
```

Now I'm trying to figure out the best way to essentially get the data in a place `queryListenerForObserver` can access it that is not the store--or figure out a way to call `observer.next` some other way. I'm not well equipped to figure that out but I'll keep trying.

**Comment by kamranayub** [comment]
I have the tests passing, I just have it use `setQuery` to set the `newData` object manually if using `no-cache`. I'll begin a PR and I will also test locally to see if it's addressing my issue...

**Comment by mshwery** [comment]
I'm getting an eerily similar issue (same data shape, despite getting a valid gql response, default fetch policy), but only when building minified production assets for the apollo-client. That leads me to believe it's something in our code, but I'm not sure if any apollo libs look for `NODE_ENV=production`.

**Comment by andrewpeterprifer** [comment]
Any updates on this?

**Comment by sreuter** [comment]
This makes things pretty much unusable for me in some cases. I tried no-cache to actually get a proper loading indicator, as with the default fetch policy loading sometimes returns false even tho data is being loaded from remote.

**Comment by audiolion** [comment]
This was fixed in release 2.3.8 by hwillson

**Comment by HRK44** [comment]
I'm still having this issue (data is {}) on 2.4.2

**Comment by hikire** [comment]
same here, on 2.4.2

**Comment by AdelBachene** [comment]
I'm still having this issue with the latest version 2.4.5

`"apollo-client": {
            "version": "2.4.5",
            "requires": {
                "@types/async": "2.0.50",
                "@types/zen-observable": "^0.8.0",
                "apollo-cache": "1.1.20",
                "apollo-link": "^1.0.0",
                "apollo-link-dedup": "^1.0.0",
                "apollo-utilities": "1.0.25",
                "symbol-observable": "^1.0.2",
                "zen-observable": "^0.8.0"
            },`

**Comment by thanpolas** [comment]
@kamranayub this issue still persists randomly.

From what we could gather, for no apparent reason, once every few times (less than 10 in our case) the Query component will trigger twice when `fetchPolicy` is set to `no-cache`. The first invocation will have the data, the second invocation will not.

We have replaced all our "no-cache" policies with "network-only" and will continue monitoring.

Please re-open this issue or let me know if I need to open a new one.

**Comment by olistic** [comment]
I have the same issue as @thanpolas, also happening erratically. Running version `2.3.1` of `react-apollo`. If I `console.log` the `networkStatus`, I see that in the cases where it breaks it logs:

```
networkStatus = 1
networkStatus = 7
networkStatus = 7
```

instead of the expected:

```
networkStatus = 1
networkStatus = 7
```

**Comment by signal-intrusion** [comment]
Confirming that this is still an issue. We're encountering this when mocking network requests during E2E tests with Cypress.

**Comment by jdorleans** [comment]
After several trails I figured `data` is always null whenever there are missing fields from the projected result. For instance, if we're supposed to query an user like: `user { uuid email picture }` and for some reason the server does not return field `picture`, then result will be:
```
{
  data: null
  loading: false
  networkStatus: 7
  stale: true
}
```
I've also noticed we'll get a `Missing field picture` warning on the console.

In my particular case, my backend never serializes `null` values. Since user's picture and many others fields are optional (nullable), we constantly face this problem.

Does anyone have an idea why those missing fields break the result causing this issue?

**Comment by mariozig** [comment]
We encountered this issue and resolved via help from @jdorleans's comment. When the response does not include a field you're expecting the entire `data` object will be null.

**Comment by jdorleans** [comment]
I forgot to mentioned I created a new issue (#4267) to keep track of the problem I'm facing since it might differ from this one here.

**Comment by standy** [comment]
Have same issue on apollo-client@2.4.12, why this is closed?

**Comment by v-i-n-y-a** [comment]
The same problem with the Query component. It returns normal data once, then data = {} with the same query (nothing is changed just component is rerendered) when  fetchPolicy is 'no-cache'

**Comment by rivertam** [comment]
Ironically, this happens for me when my policy is "network-only". Switching to "no-cache" (what's the difference, by the way?) fixes it.

**Comment by audiolion** [comment]
@rivertam are you using the client and setting "network-only" or the Query component?

**Comment by rivertam** [comment]
@audiolion Client in this case

**Comment by audiolion** [comment]
@rivertam use Query if you can, its a bug in apollo client, see 

- https://github.com/apollographql/react-apollo/issues/556
- https://github.com/trojanowski/react-apollo-hooks/issues/81

**Comment by below-1** [comment]
@rivertam Same here. Using Apollo Client, switch to "no-cache" solve the problem

**Comment by bozskejkaja** [comment]
I'm actually experiencing this issue from multiple sides.
In some cases, the query works "network-only" but does not work with "no-cache", whereas, in other queries, the only thing that works is "no-cache".
I've tried to see whether my issue might be related to the missing fields @jdorleans mentioned, but that does not seem to be the case.
Oh, and data indeed does seem to be `undefined` instead of `null`, as @sreuter mentioned.
Somehow, reloading the whole page does seem to solve the issue & everything is fetched properly.

Why is this closed again? There's not even a workaround, save an actual fix for this.

**Comment by andfs** [comment]
I'm with the same problem that @jdorleans.
Apollo is a great library, but I'm facing a lot of bugs :(

**Comment by harveyconnor** [comment]
Still having the same issues as @bozskejkaja 
Neither no-cache or network-only are working for me when making @client side queries.

**Comment by marticrespi** [comment]
I still having the same issues with `apollo-client@2.5.1`. It only works the first query, if you request the same data always is empty, if you change some fields it works only the first request.

**Comment by dwalintukan** [comment]
`no-cache` solved the problem for me.

**Comment by MM3y3r** [comment]
Same issue.

**Comment by andfs** [comment]
All my problems were solved with **errorPolicy: "all"**

```
const client = new ApolloClient({
      cache: new InMemoryCache(),
      link: errorLink.concat(link),
      resolvers: {},
      defaultOptions: {
        query: {
          errorPolicy: "all"
        }
      }
    });
```

**Comment by saqib-ahmed** [comment]
> After several trails I figured `data` is always null whenever there are missing fields from the projected result. For instance, if we're supposed to query an user like: `user { uuid email picture }` and for some reason the server does not return field `picture`, then result will be:
> 
> ```
> {
>   data: null
>   loading: false
>   networkStatus: 7
>   stale: true
> }
> ```
> 
> I've also noticed we'll get a `Missing field picture` warning on the console.
> 
> In my particular case, my backend never serializes `null` values. Since user's picture and many other fields are optional (nullable), we constantly face this problem.
> 
> Does anyone have an idea why those missing fields break the result causing this issue?

This insight from @jdorleans resolved the issue for me.

**Comment by Platekun** [comment]
@jdorleans You have no idea how many hours you saved me. I was going in a rabbit hole trying to find the answer. Thank you
