### ISSUE TITLE
When changing variables on a query, old data is still returned until loading completes

### ISSUE THREAD

**Issue by clayne11** [apollographql/apollo-client#3550]
**Intended outcome:**
When I change the variables on a query, the loading state flips to true, and if there is no data in the cache associated with those variables, data is returned as undefined.

**Actual outcome:**
When I change the variables on a query, the loading state flips to true, but the data associated with the old variables is still returned from render until loading completes, at which point the new data is returned.

**How to reproduce the issue:**

1. Pass variables to a Query.
1. Update those variables.
1. Observe the results.

**Versions**
  System:
    OS: macOS Sierra 10.12.6
  Binaries:
    Node: 8.9.1 - ~/.nvm/versions/node/v8.9.1/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 5.5.1 - ~/.nvm/versions/node/v8.9.1/bin/npm
  Browsers:
    Chrome: 66.0.3359.181
    Firefox: 58.0.1
    Safari: 11.1.1

This definitely seems like a bug to me. If the variables change then the data returned from the cache for the combination of the variables + the query should be empty until there are results from the network.

**Comment by deftomat** [comment]
Looks like a bug to me too... We cannot show the old data when filter/variable has changed.

**Comment by chilltemp** [comment]
I actually like this behavior.  I blur the old data while loading the new.  It prevents my auto-resizing components from jumping around while loading.  However, I think this should be opt-in, or at least very clearly documented.

**Comment by clayne11** [comment]
@chilltemp it's definitely a bug. The behavior you're describing can be achieved using React state and lifecycle methods. The behavior I describe, however, is impossible to achieve without this fix since there's no way to know that the data you are receiving isn't related to the variables that are currently being passed into the query.

**Comment by ribas1a3** [comment]
+1

**Comment by tronin** [comment]
+1

**Comment by tgritter** [comment]
+1

**Comment by tronin** [comment]
Hi, guys, I fixed it! have you check your query and if you have duplicated queries in your project you will have cached data in Apollo <Query />. Apollo thinking that you try to refetch your latest query instead to make the new one. 

Do not use duplicated queries in separate components.

**Comment by deftomat** [comment]
@tronin The problem is that query looks the same but variables are different.

**Comment by shanidar** [comment]
Hi, I have the same issue, same query with different variable returns old data from cache

**Comment by saschb2b** [comment]
For me changing the fetch-policy worked. But no I have no cache
```
fetchPolicy="network-only"
```
to
```
fetchPolicy="no-cache"
```

**Comment by tafelito** [comment]
is this an issue or is intended by design? Because this is still happening in apollo v3

**Comment by faq885** [comment]
still having this error with client.query method in 2020 :( i had to avoid using cache

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!

**Comment by castor55** [comment]
You can use `clearCache()` to clear the local cache.
https://www.apollographql.com/docs/ios/caching/
