### ISSUE TITLE
GraphQL subscriptions never complete

### ISSUE THREAD

**Issue by jer-sen** [apollographql/apollo-client#4163]
**Intended outcome:**

When I subscribe to a GraphQL subscription, if the server sends a `GQL_COMPLETE` (ie when `AsyncIterator` in resolver returns `{ done: true }`), on the client any Observable subscribed to the QraphQL subscription should complete.

**Actual outcome:**

`complete` functions of subscribed Observables are not called.

**How to reproduce the issue:**

Follow the doc to set up a server and client with a GraphQL subscription.
Then change the subscription's resolver with something like that:

```
import { $$asyncIterator } from 'iterall';
...
subscribe: function() {
	return {
		next: function() {
			// this will make the server send GQL_COMPLETE at the first iteration
			return Promise.resolve({ value: undefined, done: true });
		},
		return: function() {
			return Promise.resolve({ value: undefined, done: true });
		},
		throw: function(error) {
			console.log("error");
			return Promise.reject(error);
		},
		[$$asyncIterator]: function() {
			console.log("iter");
			return this;
		},
	};
},
```

**Versions**

```
  System:
    OS: Windows 10
  Binaries:
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    apollo-cache-inmemory: ^1.3.0 => 1.3.10
    apollo-client: ^2.4.2 => 2.4.6
    apollo-link: ^1.2.3 => 1.2.3
    apollo-link-context: ^1.0.9 => 1.0.9
    apollo-link-error: ^1.1.1 => 1.1.1
    apollo-link-ws: ^1.0.9 => 1.0.9
    apollo-upload-client: ^9.0.0 => 9.1.0
    react-apollo: ^2.2.3 => 2.3.1
```

**Solution**
Add these lines here https://github.com/apollographql/apollo-client/blob/11aad8151e0d383bf5bdfcba5194112e4ce809e2/packages/apollo-client/src/core/QueryManager.ts#L934:
```

complete: () => {
  observers.forEach(obs => {
    if (obs.complete) {
      obs.complete();
    }
  });
},
```

**Comment by sijad** [comment]
I have exactly same issue, @jay1337's solution works.

**Comment by ioanlucut** [comment]
+1

**Comment by sijad** [comment]
I think main issue here has been fixed in v3

you can use this repo for example: https://github.com/sijad/test-apollo-ws/blob/8f496f4b7772a2534e2ef02347ab4392c5d40e23/front/src/App.js#L18

but I'm not sure about `observable-to-promise` problem

**Comment by ioanlucut** [comment]
Hi @sijad. Thank you for answering. By V3 you mean https://github.com/apollographql/apollo-client/blob/master/CHANGELOG.md#apollo-client-vnext-1 ?

**Comment by sijad** [comment]
@ioanlucut sorry I mixed up version `apollo-client` with `apllo-react` by mistake.

`apollo-client` version in my example is `^2.6.4` and client get notified when server closes the connection via `onSubscriptionComplete`.

in `react-apollo`, `loading` always stays `true` even if connection has been completed which I think it's a different issue...

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!

**Comment by sebastienbarre** [comment]
It is still happening for me as of today with 3.2.4. My subscription's `completeCallback` is never called when I subscribe to a `watchQuery`. I assume I'm doing something wrong, because I don't see what good an observable is for if you don't know when it has completed...

**Comment by cabljac** [comment]
Hi, has this been fixed? I think i'm also running into this issue.
