### ISSUE TITLE
Unable to resolve "graphql/language/visitor" from "node_modules/apollo-utilities/lib/bundle.umd.js"

### ISSUE THREAD

**Issue by Truemedia** [apollographql/apollo-client#4485]
**Intended outcome:**
Trying to use Apollo client with React native or Vue native using code from this recipe page
https://www.apollographql.com/docs/react/recipes/react-native.html

Running the iOS simulator expect to see an app or error messages directly related to my app.

**Actual outcome:**
When running the iOS simulator I get the message:
```bash
Unable to resolve "graphql/language/visitor" from "node_modules/apollo-utilities/lib/bundle.umd.js"
```

Extra message is module does not exist in haste map

**How to reproduce the issue:**
Create a fresh React or vue native instance and try using the apollo client for a simple query

**Versions**
System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.119
    Safari: 12.0.3
  npmPackages:
    apollo-client: ^2.4.13 => 2.4.13 
    react-apollo: ^2.4.1 => 2.4.1

**Comment by christiansr85** [comment]
The same is happening to me, but trying to run my application on Windows 10 on an Android emulator and even on my android phone throug `Expo `(v32.0.0).

**Comment by dysonpro** [comment]
`apollo-utilities` v1.1.3 has a dependency on `graphql` which is not mentioned in its package.json
but it is mentioned as a peerDependency for `Apollo-client`
to resolve it, I ran: `npm install -s graphql`

**Comment by christiansr85** [comment]
@dysonpro that's it... I totally forgot to check my installed dependecies...

**Comment by benjamn** [comment]
The `graphql` package is a [peer dependency](https://github.com/apollographql/apollo-client/blob/d21e5ed3c071316b8ba51138ddaa39520540307a/packages/apollo-utilities/package.json#L39) of `apollo-utilities` now, which is our general policy for Apollo packages because we really don't want multiple copies of `graphql` getting installed, since that [throws `instanceof` for a loop](https://github.com/graphql/graphql-js/blob/c3292db017a6f20c8249f525b452d20e76ab6fae/src/jsutils/instanceOf.js).

**Comment by ssalbdivad** [comment]
For those still affected by this apollo-cache and graphql-anywhere also depend on graphql but don't list it as a peerDependency. PR with a fix:
https://github.com/apollographql/apollo-client/pull/5081

**Comment by oknoorap** [comment]
hey i still got error, even after installing `yarn add graphql`

**Comment by RuneKR** [comment]
I still have the issue after npm install graphql. Just like #https://github.com/Polymer/pwa-starter-kit/issues/362

**Comment by mateomarconi** [comment]
> hey i still got error, even after installing `graphql` via `yarn add graphql`

Here too

**Comment by RuneKR** [comment]
Hi, everyone. I managed to fix it. Created a Clean PWA Starter kit that works.
- https://github.com/RuneKR/pwa-typescript-webpack-starter

Key things i did:
- Set babel-loader sourceType to "unambiguous"
- Set @babel/plugin-transform-runtime useESModules true

See the webpack config folder. The current webpack config is quite minimal but happy to extend it.

**Comment by LucHermkens** [comment]
I'm getting the following error:

```sh
Failed to compile.

./node_modules/apollo-client/bundle.esm.js
Attempted import error: 'BREAK' is not exported from 'graphql/language/visitor'.
```

Do you guys have any idea what might cause this issue? I have `graphql@^14.5.8`, `apollo-boost@^0.4.4` and `@apollo/react-hooks@^3.1.3`. Thanks for the help! :smile:

**Comment by LucHermkens** [comment]
> I'm getting the following error:
> 
> ```shell
> Failed to compile.
> 
> ./node_modules/apollo-client/bundle.esm.js
> Attempted import error: 'BREAK' is not exported from 'graphql/language/visitor'.
> ```
> 
> Do you guys have any idea what might cause this issue? I have `graphql@^14.5.8`, `apollo-boost@^0.4.4` and `@apollo/react-hooks@^3.1.3`. Thanks for the help! 😄

I managed to fix this by adding '.mjs' to the list of filetypes for Webpack to resolve. Full example:

```js
{
  test: [/\.js$/, /\.mjs$/],
  loader: require.resolve('babel-loader'),
  options: {
    ...
  }
}
```

**Comment by xtop-io** [comment]
Same issue there:

`Unable to resolve "../graphql/client/fetchUser.graphql" from "pages/index.tsx"`
under iOS simulator.
Is there any way to fix that issue?

**Comment by RuneKR** [comment]
@annabfenske  - have a look at what i did to my own project to make it work. You can make the same changes to your bundler to make it work.

**Comment by Mdelacruzmelo** [comment]
I fixed by reading the documentation of Graphql - authentication

import { ApolloClient, createHttpLink, InMemoryCache } from '@apollo/client';
import { setContext } from '@apollo/client/link/context';

const httpLink = createHttpLink({
  uri: '/graphql',
});

const authLink = setContext((_, { headers }) => {
  // get the authentication token from local storage if it exists
  const token = localStorage.getItem('token');
  // return the headers to the context so httpLink can read them
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : "",
    }
  }
});

const client = new ApolloClient({
  link: authLink.concat(httpLink),
  cache: new InMemoryCache()
});

**Comment by Mdelacruzmelo** [comment]
I got the error:
"graphql/language/visitor" from "node_modules/apollo-utilities/lib/bundle.umd.js"

beacuse i was importing "setContext" like this:
"import { setContext } from 'apollo-link-context'"

I just changed to this :
"import { setContext } from '@apollo/client/link/context'"

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!

**Comment by atifjkhan** [comment]
i still have this error, i ran nextjs and nodejs on ubuntu server, i know its a very bad way to enable on server but im just testing, im planning to start it using pm2.
