### ISSUE TITLE
Why is client nullable in MutationResult type?

### ISSUE THREAD

**Issue by fromi** [apollographql/apollo-client#6374]
Using Typescript, I notice that when I use `useQuery`, [I collect a non nullable 'client' property.](https://github.com/apollographql/apollo-client/blob/c2698e5fdbd109a4765ce269d345b20cfccc0ec9/src/react/types/types.ts#L80)
However, with `useMutation`, [it is nullable.](https://github.com/apollographql/apollo-client/blob/c2698e5fdbd109a4765ce269d345b20cfccc0ec9/src/react/types/types.ts#L192)

This does not seems right: to get a mutation result, one must have an Apollo Client.
Is this intended or is it a mistake in the typing?

**Comment by fromi** [comment]
I have another related question:
When I do this:
```
  const [addTodo] = useMutation<{ addTodo: Todo }>(CREATE_GAME, {
    update: (cache, {data}) => {
      // data can be null or undefined: why?
    }
  })
```
The data passed in the update function can be null or undefined. Why is that?

**Comment by jeffreyffs** [comment]
@fromi Default graphql behaviour is `null | T` if you don't specify it is a required field. Apollo then adds on the possibility of `undefined` if the data hasn't loaded yet. Hence you end up with `null | undefined | T`. If you update your schema to say the field is required (adding a !), you will end up with `undefined | T`

**Comment by fromi** [comment]
@jeffreyffs Here we are inside an "update" function of a mutation: why can it be undefined? If we run the function, it mean that it has returned, so the data has loaded.
Regarding the 'null', I already have ! everywhere in my schema. This mutation returns a non nullable object, so data should not be null either.
See type MutationUpdaterFn in the source code: mutationResult is a FetchResult, whereas I think it could be some "ResolveFetchResult" where data cannot be null.

**Comment by jeffreyffs** [comment]
You've forced the type of your `useMutation` here with `useMutation<{ addTodo: Todo }>`... there is no`!` so, it is nullable as far as the mutation is concerned.

I could see an argument for having it not be `undefined` though. It will never be in a loading state, as you have already finished the mutation.

**Comment by fromi** [comment]
I am not exactly forcing the type, I am specifying it. Otherwise data has "any" type, which indeed cause no warning or compilation error of any kind, which is not what I want.
I cannot specify a type for data which is not nullable, it is declared as so in the framework.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!

**Comment by fromi** [comment]
There is no change in the latest version of Apollo:
The type `MutationUpdaterFn` [defined here](https://github.com/apollographql/apollo-client/blob/90235f8f0cf6145a7da04b58c9f37760e57a99ed/src/core/watchQueryOptions.ts#L279) uses the type `FetchResult` [defined here](https://github.com/apollographql/apollo-client/blob/90235f8f0cf6145a7da04b58c9f37760e57a99ed/src/link/core/types.ts#L23), which `data` property can be undefined.
In the context of a mutation updater function, data is never null so the typing is no has good as it can be.

**Comment by hwillson** [comment]
Happy to look at a PR that addresses this @fromi - thanks!

**Comment by emilio-martinez** [comment]
@hwillson can you share what the rationale is behind the `data` property in `FetchResult` being potentially undefined or null? I'm happy to put a PR in place for that, but I assume it was set that way for a reason? Or is it just an oversight?

**Comment by apieceofbart** [comment]
I think this is a bug - I don't see a case where mutationResult in useMutations' hook can be undefined and clearly apollo authors did not provide any such case. It looks like someone was lazy writing the types definition and just added null | undefined without much thinking

**Comment by benjamn** [comment]
This has been fixed since `@apollo/client@3.1.0`, thanks to https://github.com/apollographql/apollo-client/pull/6617.

**Comment by effektsvk** [comment]
That PR only fixes the `client` being optional, `data` property is still optional inside of `update` function. Is it safe to just assume that `data` will be always there?

**Comment by tetchel** [comment]
As pointed out above, I think this issue should still be open unless a reason is given why `.data` may be undefined.

**Comment by tetchel** [comment]
I found this in the documentation, which gives a reason for undefined-ness of data, but that could be fixed with some stricter typing: https://www.apollographql.com/docs/react/api/react/hooks/#data

![image](https://user-images.githubusercontent.com/8888438/159174378-2d3e5da2-9336-4d05-aee5-e2c956a980c5.png)

**Comment by IdkMan2Usertive** [comment]
The problem still exists and is very bothersome.
As @tetchel mentioned, we could have some stricter typings.
