### ISSUE TITLE
TypeError: tsInvariant.setVerbosity is not a function

### ISSUE THREAD

**Issue by sashberd** [apollographql/apollo-client#9094]
Just updated to latest version to apollo and on local run I get this error:

```
TypeError: tsInvariant.setVerbosity is not a function
    at Object../node_modules/@apollo/client/core/core.cjs (/Users/alexmacbook/Desktop/DEV/floki/.next/server/static/development/pages/index.js:83252:13)
    at __webpack_require__ (/Users/alexmacbook/Desktop/DEV/floki/.next/server/static/development/pages/index.js:29:31)
    at Object../node_modules/@apollo/client/main.cjs (/Users/alexmacbook/Desktop/DEV/floki/.next/server/static/development/pages/index.js:84045:12)
    at __webpack_require__ (/Users/alexmacbook/Desktop/DEV/floki/.next/server/static/development/pages/index.js:29:31)
    at Module../pages/index.js (/Users/alexmacbook/Desktop/DEV/floki/.next/server/static/development/pages/index.js:92980:72)
    at __webpack_require__ (/Users/alexmacbook/Desktop/DEV/floki/.next/server/static/development/pages/index.js:29:31)
    at Object.3 (/Users/alexmacbook/Desktop/DEV/floki/.next/server/static/development/pages/index.js:97602:18)
    at __webpack_require__ (/Users/alexmacbook/Desktop/DEV/floki/.next/server/static/development/pages/index.js:29:31)
    at /Users/alexmacbook/Desktop/DEV/floki/.next/server/static/development/pages/index.js:124:18
    at Object.<anonymous> (/Users/alexmacbook/Desktop/DEV/floki/.next/server/static/development/pages/index.js:127:10)
```
I tried to add tsInvariant as dev dependency, but still no luck. Anyway, why I need any ts lib if I use simple React?

```
 "@apollo/client": "^3.5.4",
  "react": "^16.8.4",
```

**Comment by benjamn** [comment]
@sashberd Do you see anything installed in `node_modules/ts-invariant/`? If so, what `version` do you see in `ts-invariant/package.json`? Are there multiple copies of `ts-invariant` installed (try running `npm ls ts-invariant`)?

**Comment by sashberd** [comment]
@benjamn FYR

<img width="1626" alt="Screen Shot 2021-11-23 at 9 53 09" src="https://user-images.githubusercontent.com/11975561/142987657-642140ca-6ad3-414d-a60e-b4b09c6fa261.png">
There is only 1
version 0.4.4

**Comment by saarhaber** [comment]
Hi, I am facing a similar issue.

I updated to version 3.5.5 (to fix the ts-invariant/process issue that was solved in 3.5.4).

What I see when I run it:
![image](https://user-images.githubusercontent.com/37675905/143300086-865cea8e-011f-4641-9b01-196544e2f90e.png)

In `ts-invariant/package.json` I have version 0.9.3
When I run `npm ls ts-invariant` I see:
![image](https://user-images.githubusercontent.com/37675905/143300476-5d57d8a5-7dbd-40c4-8166-6dc5e3f4f8df.png)

Any idea how to solve it? Thanks.

**Comment by benjamn** [comment]
@saarhaber Does `node_modules/@apollo/client/node_modules/ts-invariant/package.json` exist? It should have `"version": 0.9.3` (the latest version), and the `@apollo/client` package should be importing from that version of `ts-invariant` and not any other version.

Ideally there would only be one copy of `ts-invariant` installed, but multiple copies are legal and should operate independently. You might also try removing `graphql-anywhere` unless you're actually using it, though I don't expect that to fully solve this problem.

**Comment by saarhaber** [comment]
With Yarn resolutions and version 0.9.3 the issue is gone. Thanks!

**Comment by sashberd** [comment]
@benjamn I still have this issue after update to latest version
Here the SS for command you asked me before:
<img width="467" alt="Screen Shot 2021-12-29 at 15 37 12" src="https://user-images.githubusercontent.com/11975561/147667922-67865def-e686-44e2-ae07-b19f38d451df.png">
Any updates how to workaround this one?

**Comment by evan-sheehan** [comment]
I'm having the same issue for what it's worth, but I seemingly only have one version of ts-invariant installed: 
![image](https://user-images.githubusercontent.com/67272025/148949256-7b4c95cc-aa5d-45ce-936e-196b865c5e57.png)

**Comment by evan-sheehan** [comment]
Fixed my issue per this StackOverflow post: https://stackoverflow.com/questions/70615613/apollo-client-named-export-remove-not-found

In my SvelteKit/Vite project I added this to the svelte.config for the vite config settings: 
![image](https://user-images.githubusercontent.com/67272025/148998707-32bab234-ba5f-4c1c-95e2-0cd639e27679.png)

I also needed to properly import Apollo client functions via "@apollo/client/core/index.js". Don't think this will help OP, but might be useful for someon else.

**Comment by phryneas** [comment]
Hi everyone, I'm doing some housekeeping on old issue.

With Apollo Client 4.0, we are no longer using `ts-invariant`, so this issue should not occur anymore.

For details on the Apollo Client 4.0 release, please see [this announcement blog post](https://www.apollographql.com/blog/announcing-apollo-client-4-0), [the migration guide](https://www.apollographql.com/docs/react/migrating/apollo-client-4-migration) and the [changelog](https://github.com/apollographql/apollo-client/releases/tag/%40apollo%2Fclient%404.0.0).

I am going this issue as I think it is resolved - please don't hesitate to open new issues if this is still occurring.

Have a great day everyone!
